# This is for a MinGW-32 system running on Windows. Only been checked on a Windows 10 system.
# For now, macxx has to be built to run in 32 bit mode.

HOST_CPU = -m32
DELIM = ^
ARM32 = 0
LINUX = 0
MSYS2 = 0
MINGW = 1
DBG = #-g 
CC = mingw32-gcc
ECHO = echo

include Makefile.common

