# This is for a MSYS2 version running on Windows. Only been checked on a Windows 10 system.
# For now, macxx has to be built to run in 32 bit mode.
# What I had to do to build with MSYS2 is open a cmd window, cd to the MSYS top dir and run the
# buildtools-32.bat file to get the environment setup for 32 bit builds.

HOST_CPU = -m32
DELIM = '
ARM32 = 0
LINUX = 1
MSYS2 = 1
MINGW = 0
DBG = #-g 
CC = gcc
ECHO = echo

include Makefile.common




