# This is for a MinGW-32 system running on Windows. Only been checked on a Windows 10 system.
# For now, macxx has to be built to run in 32 bit mode.

HOST_CPU = -m32
DELIM = ^
PiOS32 = 1
LINUX = 0
MSYS2 = 0
MINGW = 1
EXTRA_DEFINES = -DMINGW
EXTRA_CHKS =
DBG = 
OPT = -O2
CC = mingw32-gcc
ECHO = echo
RM = CMD /C DEL /Q/S
RMDIR = CMD /C RMDIR /Q/S

include Makefile.common

