# This is for a MSYS2 version running on Windows. Only been checked on a Windows 10 system.
# For now, macxx has to be built to run in 32 bit mode.
# Double click on the buildtools-32.bat or mingw32.exe file in your toplevel MSYS2 directory.

HOST_CPU = -m32
DELIM = '
PiOS32 = 0
LINUX = 0
MSYS2 = 1
MINGW = 0
EXTRA_DEFINES = -DMSYS2
EXTRA_CHKS =
DBG = 
OPT = -O2
CC = gcc
ECHO = echo
RM = rm -f 
RMDIR = rm -rf

include Makefile.common




